### PR TITLE
c-lightning-REST: Fix wrong `getChannels` endpoint

### PR DESCRIPTION
**Pull request by sha-265**
# Description

Relates to issue: **ZEUS-[1253](https://github.com/ZeusLN/zeus/issues/1253)**

As mentioned in issue https://github.com/ZeusLN/zeus/issues/1253 the channel list is not working with CLN-REST backend.

If I understand correctly, `getChannels` should return the list of channels connected or opened to the node.

According to [CLN documentation](https://lightning.readthedocs.io/lightning-listchannels.7.html), `listchannels` endpoint returns channels that are known to the node:
> The listchannels RPC command returns data on channels that are known to the node

It's counterintuitive, but the correct endpoint is `listpeers` which, according to the [CLN documentation](https://lightning.readthedocs.io/lightning-listpeers.7.html), should return all the connected peers/open channels with the node:
> The listpeers RPC command returns data on nodes that are connected or are not connected but have open channels with this node

As I see `sparko` backend [also using](https://github.com/ZeusLN/zeus/blob/master/backends/Spark.ts#L65) `listpeers` and not `listchannels`. 

Anyway, there is required data that filtered out by the `CLN-REST` team for some reason, so I'm trying to remove this filter here https://github.com/Ride-The-Lightning/c-lightning-REST/pull/153.

Before & after:
image
 image

This pull request is categorized as a:

- [ ] New feature
- [x] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance 
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] LND (REST)
- [ ] LND (Lightning Node Connect)
- [x] Core Lightning (c-lightning-REST)
- [ ] Core Lightning (Spark)
- [ ] Eclair
- [ ] LndHub

### CODE REVIEW

**Comment by sha-265** [comment]
@kaloudis

**Comment by kaloudis** [comment]
@sha-265 have you tested this?

**Comment by sha-265** [comment]
> @sha-265 have you tested this?

@kaloudis what do you mean by tested? As you can see in the screenshots, before this fix channel view is not working at all, and after, it's working fine. 

If you mean if I ran `yarn run tsc` so yes, but there were errors unrelated to my changes.

**Comment by kaloudis** [comment]
Excellent. I will keep track of the CLR issue.

To confirm, it doesn't work without that change on their repo, correct?

**Comment by sha-265** [comment]
> To confirm, it doesn't work without that change on their repo, correct?

Yes, that's right. Their code is filtering some crucial data.

**Comment by sha-265** [comment]
@kaloudis, fix has been merged to the new release of CLN-REST, [v0.10.0](https://github.com/Ride-The-Lightning/c-lightning-REST/releases/tag/v0.10.0).

Can you proceed with this PR so we can merge this fix to Zeus?

Thanks.

**Review by kaloudis — APPROVED** [review]

**Comment by kaloudis** [comment]
uTACK. Gonna try to get this out the door in a beta on Monday

**Pull request merged**
