### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by dscotese**
# Description

This is simply a change to the label for the fee rate so that its meaning is clearer.  Issue #339 provides more detail.

### CODE REVIEW

**Comment by kaloudis** [comment]
I think it'd be clearer to label it PPM (Parts Per Million) and multiply the value we send over currently by 1,000,000

**Comment by kaloudis** [comment]
5ah390rq

**Comment by ZeusLN** [comment]
Hey @dscotese - really appreciate the PR but closing in favor of https://github.com/ZeusLN/zeus/pull/388

**Comment by dscotese** [comment]
That's good.  I favored #388 too.

**Pull request closed without merging**
