### PR TITLE
Locales: rename 'copy node config' button to 'duplicate node config'

### PR DESCRIPTION
**Pull request by myxmaster**
# Description

Since 'copy node config' sounds like copying something to the clipboard, I renamed it to 'duplicate node config'.

This pull request is categorized as a:

- [ ] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [x] Locales update
- [ ] Quality assurance 
- [ ] Other

## Checklist
- [x] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [x] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] Core Lightning (Spark)
- [ ] Eclair
- [ ] LndHub

### Locales
- [x] I’ve added new locale text that requires translations
- [x] I’m aware that new translations should be made on the Zeus [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Review by shubhamkmr04 — APPROVED** [review]
tACK

**Review by kaloudis — APPROVED** [review]

**Review by kaloudis — CHANGES_REQUESTED** [review]
@myxmaster can you edit the commit to only modify the `en.json` file?

**Comment by myxmaster** [comment]
Does transifex automatically understand when a string was removed/renamed? I didn't expect that, that's why I deleted the discarded string name `views.Settings.AddEditNode.copyNode` in all locale files.

**Comment by kaloudis** [comment]
> Does transifex automatically understand when a string was removed/renamed? I didn't expect that, that's why I deleted the discarded string name `views.Settings.AddEditNode.copyNode` in all locale files.

Yes. Please only modify the `en.json` file

**Review by kaloudis — APPROVED** [review]

**Pull request merged**
