### PR TITLE
Password: Improve layout 

### PR DESCRIPTION
**Pull request by shubhamkmr04**
Issue: [1823](https://github.com/ZeusLN/zeus/issues/1823)

Before:
Simulator Screenshot - iPhone 14 Plus - 2023-11-04 at 20 23 03
Screenshot_1699110196
After:
Simulator Screenshot - iPhone 15 Plus - 2024-04-04 at 23 22 06

Simulator Screenshot - iPhone 15 Plus - 2024-04-04 at 23 21 44

### CODE REVIEW

**Comment by shubhamkmr04** [comment]
@kaloudis maybe we can remove the text from above the input in `Lockscreen` view and put something in Header

**Comment by kaloudis** [comment]
> @kaloudis maybe we can remove the text "Passphrase" from above the input in `Lockscreen` view and put something in Header

Let's try it

**Comment by shubhamkmr04** [comment]
[Commit #2](https://github.com/ZeusLN/zeus/pull/2107/commits/8f70ba3ef2512ad7fe3510644e79a8b05edea5a5) : Remove text "Passphrase" from above the input in Lockscreen view and put it in Header

[Commit #3](https://github.com/ZeusLN/zeus/pull/2107/commits/060c33af595c6d8787bed0f7236a65c1edda80f1) : Previously, saving an empty passphrase resulted in an error stating **Password and duress password cannot be the same** which was misleading. We have now implemented specific error messages for empty passphrases and duress passphrases to address this issue.

**Review by kaloudis — DISMISSED** [review]
LGTM

**Pull request merged**
