### PR TITLE
LNURL-auth: LNDHub: compatibility mode for Alby and BlueWallet

### PR DESCRIPTION
**Pull request by Talej**
# Description

Relates to issue: **ZEUS-0000**

LNURL-auth with LNDHub was logging in as a different user when same account was used compared to BlueWallet. 

Modified auth feature so no sha256-hash was used for LNDHub while leaving all other backends still using hash.

I haven't yet testing this with CLN or eclair.

This pull request is categorized as a:

- [ ] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance 
- [X] Other

## Checklist
- [X] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [X] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [X] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [X] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [X] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [ ] Android
- [X] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [X] LND (REST)
- [X] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] Core Lightning (Spark)
- [ ] Eclair
- [X] LndHub

### Locales
- [X] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://www.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Comment by kaloudis** [comment]
Please provide results testing the same account + creds and logging in with them on Alby and BlueWallet

**Comment by Talej** [comment]
> Please provide results testing the same account + creds and logging in with them on Alby and BlueWallet

Zeus & BlueWallet same account demo:
https://www.dropbox.com/s/bfuif2brr9lvlf8/RPReplay_Final1675721403.MP4?dl=0

**Comment by kaloudis** [comment]
Quite mixed on this. Feels like BlueWallet should be hashing. Going to speak more with Bumi to try to bridge the gap with Alby and come up with a solution moving forward for compatibility

**Comment by Talej** [comment]
> Quite mixed on this. Feels like BlueWallet should be hashing. Going to speak more with Bumi to try to bridge the gap with Alby and come up with a solution moving forward for compatibility

Okay I'll hold off on doing too much more on it for now then.

So far I have:

- Added LNURL-Auth mode setting (options for Alby, Alby-legacy & BlueWallet)
- Implemented BlueWallet (non-hashing method)
- Implemented Alby method
- Partially implemented Alby-legacy method. Not quite functioning properly yet.

**Comment by kaloudis** [comment]
@Talej ok, push up what you have if you don't mind. could you also details what Alby does differently?

**Comment by Talej** [comment]
> @Talej ok, push up what you have if you don't mind. could you also detail what Alby does differently?

The bulk of the logic is in https://github.com/ZeusLN/zeus/pull/1305/commits/9679ef8df616aa36609dc1d869fd7416dec4cd2b#diff-c9a79951959ff333d0346af355715b005942b61d3b5842a0e53552d147df6e82R81

Alby uses a hash of `lndhub://secret` and signs the hash of `message`

Alby-legacy (`settings.legacyLnurlAuth` from alby codebase) uses a different format for the secret. I think the rest should be the same but haven't managed to get it working yet.

BlueWallet seems to literally use the `lndhub://secret` as the signedMessage. Doesn't seem to hash or use the actual message for signing.

**Comment by Talej** [comment]
Some example videos from testing

1. Zeus & Alby - https://www.dropbox.com/s/6yg26l1zgf0d0qi/zeus-alby.MP4?dl=0
2. Zeus & BlueWallet - https://www.dropbox.com/s/yfx3radwcz26spb/zeus-bw.MP4?dl=0
3. Zeus (this PR) & Zeus v0.7.2 - https://www.dropbox.com/s/tixalllmjji94b3/zeus-zeus.MP4?dl=0

**Review by kaloudis — APPROVED** [review]
tACK. great job!

**Pull request merged**
