### PR TITLE
Disaster Recovery: Optimize Spacing

### LINKED ISSUE #1733: Enhancement: Optimize spacing between elements in disaster recovery screen
To help users immediately understand to which button the text belongs, we can optimize spacing.

Right now:
grafik

Mockup:
grafik

### PR DESCRIPTION
**Pull request by myxmaster**
# Description

This fixes #1733.

Before:
grafik

After:
grafik

This pull request is categorized as a:

- [ ] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance 
- [x] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [x] Embedded LND
- [ ] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] LndHub
- [ ] [DEPRECATED] Core Lightning (Spark)
- [ ] [DEPRECATED] Eclair

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Review by shubhamkmr04 — COMMENTED** [review]
Everything on this view looks scattered. What we can do is like
Putting the buttons first here, then their info, or maybe we can only display buttons here and some icon that will open a popup containing info for every particular button
@kaloudis, what are your thoughts on it?

**Comment by shubhamkmr04** [comment]
> > My suggestion would be to put the buttons first here, then their info
> 
> That is exactly how it is :D But because of misleading margins it was not easy to understand. With this update it should be more obvious.
> 
> But I agree it is still not perfect. I do like the idea of explainers for each button.

Ohh sorry. I meant the info should be displayed first, I got confused there. :( But yeah, we'll have to iterate it so many times to make it perfect.

**Comment by kaloudis** [comment]
Would line separators help here potentially?

**Comment by shubhamkmr04** [comment]
> Would line separators help here potentially?

Yup, we can try that.

**Comment by kaloudis** [comment]
I think this looks better. Whatcha think @myxmaster?

**Comment by shubhamkmr04** [comment]
> Yeah, with this there shouldn't be any confusion anymore.
> 
> But please make the marginTop for the buttons the same as maginBottom for the text :D

Sure. Would you like me to open a PR for these changes since I can't push the committed changes in this PR?

**Pull request closed without merging**
