### PR TITLE
Pr/394

### PR DESCRIPTION
**Pull request by MONIMAKER365**
# Description

Relates to issue: **ZEUS-0000**

_Please enter a description and screenshots, if appropriate, of the work covered in this PR_

This pull request is categorized as a:

- [x] New feature
- [x] Bug fix
- [x] Code refactor
- [x] Configuration change
- [x] Locales update
- [ ] Other

## Checklist
- [x] I’ve run `npm run tsc` and make sure my code didn’t produce errors 
- [x] I’ve run `npm run prettier` and formatted my code correctly

## Testing

If you added new functionality or fixed a bug, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [ ] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [x] LND
- [x] c-lightning-REST
- [x] spark
- [x] Eclair
- [x] LndHub

### Locales
- [ ] I’ve added new locale text that requires translations
- [x] I’m aware that new translations should be made on the Zeus [Transfix page](https://www.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [x] Contributors will need to run `npm install` after this PR is merged in
- [x] 3rd party dependencies have been modified:
    * verify that `package.json` and `package-lock.json` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [x] Changes were made that require an update to the README
- [x] Changes were made that require an update to onboarding

### CODE REVIEW

**Review by MONIMAKER365 — COMMENTED** [review]
.eslintrc.jsutils/stores/backends/Spark.ts

**Comment by kaloudis** [comment]
@MONIMAKER365 I don't understand what you're trying to accomplish here. Care to explain? Maybe I can help.

**Review by MONIMAKER365 — COMMENTED** [review]
.eslintrc.js

**Comment by MONIMAKER365** [comment]
.eslintrc.js

**Review by MONIMAKER365 — COMMENTED** [review]
backends/Spark.ts

**Review by MONIMAKER365 — COMMENTED** [review]
done

**Pull request merged**
