### PR TITLE
Keysend troubleshooting

### PR DESCRIPTION
**Pull request by kaloudis**
Troubleshooting keysends for LND v0.14+

So far:

- Removed old `v1` endoint, always run through `/v2/router/send`
- Fixed timeout to 60s (pertinent to `react-native-tor` work we'll do later this week or next)
- Removed timeout field from view

### CODE REVIEW

**Comment by kaloudis** [comment]
Regular payments work, regular payments with amp work, just getting `FAILURE_REASON_INCORRECT_PAYMENT_DETAILS` on keysends

**Comment by kaloudis** [comment]
Welp, looks like my regtest counterparties just didn't have ``--accept-amp`` enabled. All works now.

**Comment by deregs** [comment]
The logic as of now will try to send an amp keysend if the connected node supports amp. I think if amp keysends are to be supported, it should really be checking if the node on the receiving end of the keysend supports amp as well. Not sure if it's even possible to check that though.

**Comment by kaloudis** [comment]
@deregs created an issue to track here: https://github.com/ZeusLN/zeus/issues/750

**Pull request merged**
