### PR TITLE
Fee Rates: remove confusing mili msat label in favor of PPM

### PR DESCRIPTION
**Pull request by kaloudis**
# Description

Relates to issue: [**ZEUS-339**](https://github.com/ZeusLN/zeus/issues/339)

5ah390rq

This pull request is categorized as a:

- [ ] New feature
- [x] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Other

## Checklist
- [ ] I’ve run `npm run tsc` and make sure my code didn’t produce errors 
- [ ] I’ve run `npm run prettier` and formatted my code correctly

## Testing

If you added new functionality or fixed a bug, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [ ] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] LND
- [ ] c-lightning-REST
- [ ] spark
- [ ] Eclair
- [ ] LndHub

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://www.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `npm install` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `package-lock.json` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Comment by kaloudis** [comment]
@fiatjaf let me know what you think

**Comment by Jestopher-BTC** [comment]
Very happy to see this change to ppm!

**Comment by Jestopher-BTC** [comment]
I would recommend defining as "parts per million" as in "1 part fee per million routed." Defining as "point per million" is less clear as it suggests a different point unit when the fee rate is unitless as sat/sat.

**Comment by dscotese** [comment]
I agree with "Parts" per million rather than "points" per million.  Otherwise, I'd provide an approving review.

**Comment by fiatjaf** [comment]
I think it is good.

**Comment by kaloudis** [comment]
Nice catch y'all! Label has been corrected.

**Pull request merged**
