### PR TITLE
Update react-native to 0.72.10

### PR DESCRIPTION
**Pull request by myxmaster**
# Description

Updated react-native to 0.72.10 in preparation for update to 0.73.

Also updated other react-native related packages and metro config. Podfile might need to be updated.

This pull request is categorized as a:

- [ ] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance
- [x] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] Embedded LND
- [x] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] LndHub
- [ ] [DEPRECATED] Core Lightning (Spark)
- [ ] [DEPRECATED] Eclair

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the ZEUS [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [x] Contributors will need to run `yarn` after this PR is merged in
- [x] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Comment by kaloudis** [comment]
We have a blocker here. We need to upgrade the docker image in our `build.sh` reproducible builds script to something with a higher version of NodeJS

`error @react-native/babel-preset@0.73.21: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"`

https://github.com/react-native-community/docker-android/blob/v7.0/Dockerfile#L22

react-native-community/docker-android v8.0 - v13.0, use NodeJS v18

**Comment by kaloudis** [comment]
Working on the Docker image bump here: https://github.com/ZeusLN/zeus/pull/1995

**Review by shubhamkmr04 — COMMENTED** [review]
tACK

**Comment by kaloudis** [comment]
iOS Podfile.lock and project file updated (new RN fixed an annoying bug with the build flags repeating)

**Comment by kaloudis** [comment]
Successfully running on iOS and Android. Build tests next

**Comment by kaloudis** [comment]
Successfully built on iOS and Android

**Review by kaloudis — APPROVED** [review]

**Pull request merged**
