### PR TITLE
Fix compatibility issues with CLN 23.05 in activity

### PR DESCRIPTION
**Pull request by sha-265**
# Description

Relates to issue: https://github.com/ZeusLN/zeus/issues/1464

Fix few compatibility issues with CLN 23.05 (and older).

Before fix, activity not working at all (app crashes). Now working.

And or invoice amounts was 0 (I think this bug maybe exist since CLN v0.12.0, with change https://github.com/ElementsProject/lightning/pull/5306):
image

I still unable to open specific invoice (nothing happens when tapping on invoice), but I'm not sure it's related.  

This pull request is categorized as a:

- [ ] New feature
- [x] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance 
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [ ] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] LND (REST)
- [ ] LND (Lightning Node Connect)
- [x] Core Lightning (c-lightning-REST)
- [ ] Core Lightning (Spark)
- [ ] Eclair
- [ ] LndHub

### CODE REVIEW

**Comment by Sjors** [comment]
Can't wait for the v0.7.6 release... I've been yolo paying pizza's and drinks at Paralelní Polis, since the invoice amount always shows as 0.

c-lightning v23.05, c-lightning-REST v0.10.3, Zeus 0.7.5 on Android.

**Comment by sha-265** [comment]
@Sjors I hope you don't have an open channel with 10K BTC outbound capacity in this node :P

**Comment by Sjors** [comment]
How else would you celebrate Pizza Day?

**Comment by nickfarrow** [comment]
I am still getting zero balances and activity amounts on `v7.6` and core-ln `v23.05` with sparko `v2.9`

**Comment by sha-265** [comment]
@nickfarrow, Spark/o is abandonware. You should migrate to CLN-REST.

**Comment by sha-265** [comment]
BTW, @kaloudis, maybe Spark/o "support" should be removed? Both Spark and Sparko are abandonware.

**Comment by Sjors** [comment]
I would at least mark them as "deprecated" in the dropdown. New users may have no idea what to use to connect to their node, and might just pick something at random and install it.

**Pull request merged**
