### PR TITLE
ZEUS-1419: LNURL-w fixed value patch

### PR DESCRIPTION
**Pull request by kaloudis**
# Description

Relates to issue: [**ZEUS-1419**](https://github.com/ZeusLN/zeus/issues/1419)

Fixed value LNURL-w was not able to be claimed when invoice settings were not defined as it broke the `UNSAFE_componentWillMount` block in `views/Receive`.

This pull request is categorized as a:

- [ ] New feature
- [x] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance 
- [ ] Other

## Checklist
- [x] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [x] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] Core Lightning (Spark)
- [ ] Eclair
- [ ] LndHub

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://www.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Comment by prusnak** [comment]
@kaloudis Is there a CI where can I download binaries for testing?

**Comment by kaloudis** [comment]
@prusnak not yet

**Comment by prusnak** [comment]
I tried to build via `./build.sh` but my build always fails with the following error while fetching the docker layers:

```
docker: failed to register layer: Error processing tar file(exit status 1): write /opt/android/system-images/android-21/google_apis/armeabi-v7a/system.img: no space left on device.
```

Not sure what's going on - I have plenty of disk space available.

**Comment by kaloudis** [comment]
@prusnak very interesting. what OS are you running it on?

**Comment by prusnak** [comment]
> very interesting. what OS are you running it on?

macOS 13.1

**Review by shubhamkmr04 — APPROVED** [review]
tACK

**Pull request merged**
