### PR TITLE
[v0.7.0-hermes] New Home view

### PR DESCRIPTION
**Pull request by kaloudis**
Screenshot_1652500250

TODO
- [x] New default navigation tab
- [x] New `UnitsToggle` component
- [x] Amount mode for `PinPad` that adds decimal button
- [x] Variable size of amount depending on length
- [x] Disable Send button until amount is set  
- [ ] clear amount on unit change
- [x] decide whether to show units alongside amount cc @Bosch-0 
- [ ] limit decimal places depending on units
- [ ] swap commas and decimals for appropriate fiat currencies
- [ ] shake animation/red color for amounts bigger than balance
- [ ] select account view + Receive/Send updates

### CODE REVIEW

**Comment by Bosch-0** [comment]
Yew!! 

Could we call this Home rather than default view? Just to keep things consistent with the Figma.

**Comment by kaloudis** [comment]
@Bosch-0 ok, and the old default view becomes Balance view?

**Comment by Bosch-0** [comment]
Old default view is accounts

**Comment by kaloudis** [comment]
Closing in favor of https://github.com/ZeusLN/zeus/pull/1075

**Pull request closed without merging**
