### PR TITLE
Ensure user knows that the file to import a certificate can be .crt or .cert.

### PR DESCRIPTION
**Pull request by dscotese**
# Description

Relates to issue: No issue was created.  Perhaps this was a mistake.

The instructions for installing a certificate to Android state that the certificate file must have the extension .cert.  The Android OS (at least the one on my phone) does not recognize a .cert file as a certificate, but it does recognize the .crt file.  This pull request updates the instructions to indicate that either extension is acceptable.

This pull request is categorized as a:

- [ ] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [X] Locales update
- [ ] Other

## Checklist
- [ ] I’ve run `npm run tsc` and make sure my code didn’t produce errors 
- [ ] I’ve run `npm run prettier` and formatted my code correctly
- [X] My code includes no new lines or keywords, just different text for some strings.

## Testing

If you added new functionality or fixed a bug, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [X ] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [ ] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] LND
- [ ] c-lightning-REST
- [ ] spark
- [ ] Eclair
- [ ] LndHub

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://www.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `npm install` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `package-lock.json` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Comment by ZeusLN** [comment]
Thanks for the PR.

A few things:

1. I think the type of file types accepted depends on the version of Android you're using
2. We do our translation stuff on Transifex. Here's our page: https://www.transifex.com/ZeusLN/zeus/dashboard/

**Comment by dscotese** [comment]
It does not seem possible to apply the logic I used to make the changes in my pull request through transifex.  I learned to translate "or" by looking at the lines in files for other languages which were translations of English containing "or" and then applied that to add "or .crt" in the appropriate place.  It appears that such a strategy is not compatible with transifex.

**Comment by kaloudis** [comment]
To make changes in Transifex you must first request editor access, then you should be able to apply the changes. We need to do it through Transifex because I'd prefer to have the new translations reviewed before they're pushed out

**Comment by dscotese** [comment]
Transifex wants me to specify that I know a language I don't know. I don't think I can request editor access any other way. There is no entry for English.  Perhaps the best way to proceed is to reject changes to all files except en and then wait for translators to find the change and copy it into their language.

**Comment by kaloudis** [comment]
That's probably the best course of action. Mind modifying the PR?

**Comment by dscotese** [comment]
I don't mind.  I have to figure out how to revert all but one file.  I've been looking for 10 minutes and haven't figured it out.  Maybe I'll just toss my fork and start over.  If you know how to revert a file, that would help.

**Comment by kaloudis** [comment]
```git checkout <commit_hash> -- <file>``` or make a new branch and open a new PR

**Comment by dscotese** [comment]
Replaced by #364

**Pull request closed without merging**
