### PR TITLE
MacOS: run simulator on Ventura 13.2 without Rosetta

### PR DESCRIPTION
**Pull request by joegesualdo**
# Description

Relates to issue: **ZEUS-0000**

I wasn't able to build on my M1 Macbook Air after I updated to Ventura. These changes get it building correctly in the simulator, with the added benefit of working without enabling XCode to open with Rosetta.

Here are the two things I changed:

1) Changed Excluded Architecture for the Simulator from `i386` to `arm64` in both the `zeus` and `zuesTests` targets.

Screenshot 2023-01-31 at 4 29 29 PM

2) Added a script to the Podfile to update all the pods in the same way.

> NOTE: I'm not sure how this would work for OS versions before Ventura, so that would need to be tested - without Rosetta enabled.

This pull request is categorized as a:

- [ ] New feature
- [x] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance 
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [ ] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [ ] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [ ] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [ ] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [ ] Android
- [x] iOS - Ventura 13.2 running IPhone 14 Simulator.

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] Core Lightning (Spark)
- [ ] Eclair
- [ ] LndHub

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://www.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Comment by kaloudis** [comment]
WOW - massively helpful

**Comment by kaloudis** [comment]
On Monterrey I'm hitting this issue when trying to build for iPhone 11: `Command PhaseScriptExecution failed with a nonzero exit code`

**Comment by joegesualdo** [comment]
@kaloudis I'd try the following:

- Delete `node_modules` directory
- Delete `ios/Podfile.lock` file
- Delete `ios/Pods` directory
- Delete derived data: `rm -r ~/Library/Developer/Xcode/DerivedData`
- Delete workspace file: `rm ./ios/zeus.xcworkspace`
- Reinstall node deps: `yarn install`
- Reinstall ios deps: `pod install`

Then try building again.

If you still get the error, I can look into it more.

**Comment by kaloudis** [comment]
> @kaloudis I'd try the following:
> 
>     * Delete `node_modules` directory
> 
>     * Delete `ios/Podfile.lock` file
> 
>     * Delete `ios/Pods` directory
> 
>     * Delete derived data: `rm -r ~/Library/Developer/Xcode/DerivedData`
> 
>     * Delete workspace file: `rm ./ios/zeus.xcworkspace`
> 
>     * Reinstall node deps: `yarn install`
> 
>     * Reinstall ios deps: `pod install`
> 
> 
> Then try building again.
> 
> If you still get the error, I can look into it more.

Did all of the above minus deleting the `.xcworkspace` and it worked. Nice job!

**Review by kaloudis — APPROVED** [review]

**Comment by joegesualdo** [comment]
Awesome!

**Comment by kaloudis** [comment]
@joegesualdo could you just modify this line to remove the Rosetta note? https://github.com/ZeusLN/zeus/blob/60330429eb0c31c7875b5fa889603dc94c3ff5f6/README.md#L124

**Comment by joegesualdo** [comment]
README has been updated and branch has been rebased.

**Review by kaloudis — APPROVED** [review]

**Pull request merged**
