### PR TITLE
Embedded LND: Settings > Advanced > Restore channel backups from clipboard

### PR DESCRIPTION
**Pull request by kaloudis**
# Description

This PR adds the ability for embedded node users to restore from channel backups after initial wallet recovery.

simulator_screenshot_C7C177F8-3D11-4CAB-B97E-EA3E71392BCB

simulator_screenshot_97B1EA97-F7C5-4CE7-85F2-62E4B89CA563

simulator_screenshot_84FE26AB-5731-478E-A865-81AE1F522697

simulator_screenshot_FB5C27B0-F7C2-4FA8-AEC9-5913C7971A7B

This pull request is categorized as a:

- [X] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [ ] Android
- [x] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [x] Embedded LND
- [ ] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] LndHub
- [ ] [DEPRECATED] Core Lightning (Spark)
- [ ] [DEPRECATED] Eclair

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the ZEUS [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Comment by kaloudis** [comment]
Will likely move the link to the Disaster recovery page

**Comment by kaloudis** [comment]
Before:
simulator_screenshot_7EA36C8F-0B67-4115-8187-CCD50E18EA00

After:
simulator_screenshot_C7C177F8-3D11-4CAB-B97E-EA3E71392BCB

**Review by shubhamkmr04 — COMMENTED** [review]
Screenshot_1708946513
TextInput in android looks too big, maybe we can remove  `multiline` and `numberOfLines={3}` to solve that

**Review by shubhamkmr04 — COMMENTED** [review]
Screenshot_1708947241
We can give some marginTop to the error message

**Pull request merged**
