### PR TITLE
Fix animation transition for middle action in SwippeableRow

### PR DESCRIPTION
**Pull request by aussedatlo**
# Description

Relates to issue: None

Fix animation transition for middle action in both OnchainSwippeableRow and LightningSwippeableRow.
In fact, the middle button (if supported) had a different animation width compared to other, resulting in strange result.

Before:

[Before](https://user-images.githubusercontent.com/35492518/177412569-d08b90f0-1b4f-49df-b212-7be05d01b969.webm)

After:

[After](https://user-images.githubusercontent.com/35492518/177412595-447b74df-a793-4977-9e88-df37f2a4b7ca.webm)

Tested with Nexus 5 (emulated)

This pull request is categorized as a:

- [ ] New feature
- [x] Bug fix
- [x] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance 
- [ ] Other

## Checklist
- [x] I’ve run `npm run tsc` and made sure my code compiles correctly
- [x] I’ve run `npm run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `npm run prettier` and made sure my code is formatted correctly
- [x] I’ve run `npm run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [x] LND
- [ ] c-lightning-REST
- [ ] spark
- [ ] Eclair
- [ ] LndHub

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://www.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `npm install` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `package-lock.json` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Comment by aussedatlo** [comment]
Any news on integrating this ?

**Comment by aussedatlo** [comment]
Behavior reproduced on emulated nexus 5, with LND on polar.
Updated description with before and after videos.

**Comment by kaloudis** [comment]
@aussedatlo looks great! thanks for including the videos to illustrate the change

have you tried this against LNDHub instances?

**Comment by kaloudis** [comment]
LGTM w/ LNDHub! Thanks for the PR.

**Pull request merged**
