### PR TITLE
Receive: add preset buttons for expiration time

### PR DESCRIPTION
**Pull request by kaloudis**
# Description

Adds 10 minute, 1 hour, 1 day, 1 week presets for the expiration time field and a dropdown field for the units. Dropdown also included on the Invoice settings view

https://github.com/ZeusLN/zeus/assets/1878621/730d04eb-863b-4ce0-a3db-939d6637df16

This pull request is categorized as a:

- [X] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [X] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [X] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [X] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [X] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [ ] Android
- [X] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] Embedded LND
- [X] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] LndHub
- [ ] [DEPRECATED] Core Lightning (Spark)
- [ ] [DEPRECATED] Eclair

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the ZEUS [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

### CODE REVIEW

**Review by shubhamkmr04 — COMMENTED** [review]
Screenshot_1707826149
The text Seconds, Minutes and Weeks are appearing with trailing dots.

**Comment by kaloudis** [comment]
Styles have been updated.

Android:
Screenshot_20240213_182010
Screenshot_20240213_181835

iOS:
Simulator Screenshot - iPhone 15 Pro Max - 2024-02-13 at 18 20 06
Simulator Screenshot - iPhone 15 Pro Max - 2024-02-13 at 18 18 29

**Review by shubhamkmr04 — COMMENTED** [review]
Screenshot 2024-02-14 at 9 19 11 AM
Screenshot 2024-02-14 at 9 18 48 AM

 nit: There is no border-radius in dropdown in Android

**Comment by kaloudis** [comment]
> Screenshot 2024-02-14 at 9 19 11 AM Screenshot 2024-02-14 at 9 18 48 AM
> 
> nit: There is no border-radius in dropdown in Android

Unfortunately, I can't find a way to style it

**Pull request merged**
